### ISSUE TITLE
iSparta mac 版打开后报错

### ISSUE THREAD

**Issue by yelianghetao** [iSparta/iSparta#1]
![is](https://cloud.githubusercontent.com/assets/7709524/5568365/0780d73c-8f94-11e4-8b54-56c223c07d6f.png)

**Comment by yangpeiyong** [comment]
遇到相同的问题

**Comment by guoyida** [comment]
Same here!

**Comment by huangjinhong** [comment]
Same here!

**Comment by hkz404** [comment]
@yelianghetao @yangpeiyong @guoyida @huangjinhong 
请 update 代码或者下载最新 Zip 包，进入 src 执行 `npm install`，打开 iSparta 看看还有没有问题？

**Comment by huangjinhong** [comment]
@hahnzhu 出现这个警告“npm WARN iSparta@ No license field.”

**Comment by huangjinhong** [comment]
重新安装之后png转无损webp不行吗？提示说是“程序发生错误：Error:ENOENT, no such file or directory 'xxx/xxxx/xxx/xxx.webp'”

**Comment by hkz404** [comment]
请试用最新版本：https://github.com/dreampiggy/iSparta/releases
