### ISSUE TITLE
English localization

### ISSUE THREAD

**Issue by jaumevn** [iSparta/iSparta#12]
Hi there!

Is there any possibility to localize the app to English?

Thanks

**Comment by dreampiggy** [comment]
I tries some ways, but the fact that this project use an very old version `node-webkit` framework, it's not easy to add i18n support. 

Maybe someone can use the latest `nw.js` framework to build and add node-server render for i18n support(such as run with express.js and doT template with node-i18n). Or the other way is to import a really big front-end JavaScript framework(which support template render) and rewrite many code...

I upload my translation here: #13 . If some English-spearker want to use this to support English localization, just use that to support. (Left-side is english and right-side is Simplified Chinese).

**Comment by dreampiggy** [comment]
@jaumevn  Added i18n support for English, Simplified Chinese and Traditional Chinese.

Since this repo on longer maintened, I put the release on my fork repo: https://github.com/dreampiggy/iSparta

Download directly with release: https://github.com/dreampiggy/iSparta/releases
