### ISSUE TITLE
出现程序错误到时是什么意思

### ISSUE THREAD

**Issue by longqi87** [iSparta/iSparta#19]
![image](https://user-images.githubusercontent.com/31119502/29442816-982582f6-8406-11e7-8552-fc7d940a57d6.png)

**Comment by dreampiggy** [comment]
This may because your pngs folder images size is not equal. This tool can only process the equal size of png images to one APNG image. Also pay attention to the image name (use `xxx01.png, xxx02.png...`)

Reference: [PNG如何转换为APNG ](http://isparta.github.io/how.html)

**Comment by dreampiggy** [comment]
I will find a better tips to capture this error. Or to restrict only the equal image size images can be processed. 😅

**Comment by leechie** [comment]
我也遇到这个问题，但解决了。如果你下载的32位版本，将iSparta-win32\win32\app\libs\apng里的win32文件夹重命名位win64就可以了。相同如果下做的是64位版本就上面路径下的win64改名为win32

**Comment by dreampiggy** [comment]
@leechie，谢谢，我检查一下是不是二进制移动错误了

**Comment by leechie** [comment]
@dreampiggy  生成apng压缩功能好像不生效，我分别用不压缩和压缩10%选项生成的文件大小是一样，请麻烦看下。

**Comment by dreampiggy** [comment]
@leechie 你是不是在64位系统上，下载了32位的iSparta，因为现在我看那个二进制，是根据当前操作系统位数来取的。假如你是64位系统，下载32位iSparta，会取win64目录下的文件，自然会出现问题……这个我确认有问题。应当根据打包的位数版本来取。

**Comment by leechie** [comment]
@dreampiggy  我是64位的系统，开始下载的也是64位的程序，但错误弹窗的提示是执行app\libs\apng\win32\xxxxx的错误（同一楼截图），后面下载32位的程序，提示的是执行app\libs\apng\win64\xxxxx的错误，所以我猜测可能你们弄反了，重新命名后就可以用了。

**Comment by leechie** [comment]
@dreampiggy  上面反馈的压缩选项生效的问题，刚看错了，选择10%压缩文件大小确实有减少，只是从11254KB减少到11229KB 压缩效果不明显，以为没有压缩。

**Comment by dreampiggy** [comment]
@leechie 正在重写APNG转换器，里面原来的实现逻辑是比较混乱。PNG压缩的实现方式，居然是用JS重新画了一遍，再丢进去用apngasm编码成APNG，压缩率不行，相当于没有利用到动图disposal的优化。

现在我会参考apng2webp的方式，直接对每个PNG图先用pngquant有损压缩或者使用pngout无损压缩一次（之前只有有损压缩，很多时候这样处理不好），然后apngasm编码成APNG动图，最后再用apngopt整体优化一次，效果应该会更好。

**Comment by dreampiggy** [comment]
@leechie Please check the [2.1.1 version](https://github.com/iSparta/iSparta/releases/tag/2.1.1) it should fix this issue.

**Comment by leechie** [comment]
@dreampiggy 赞！我试试

**Comment by dreampiggy** [comment]
@leechie Fixed ?

**Comment by dreampiggy** [comment]
Closed. It should be fixed in v2.1.1.
