### ISSUE TITLE
转换失败！请检查PNG文件格式，图片尺寸必须相同

### ISSUE THREAD

**Issue by burkgames** [iSparta/iSparta#20]
1、PNG序列转APNG可以正常转换
2、将此APNG转为WEBP，就弹出这个错误框
![qq 20170829111045](https://user-images.githubusercontent.com/4887816/29802905-0501b01e-8cab-11e7-895e-8c33d0d53536.png)

**Comment by burkgames** [comment]
知道了  原来是WIN7的锅  升级到Win10就可以了。。。

**Comment by dreampiggy** [comment]
我检查一下libwebp 0.6.0的兼容性，是不是不支持Win7，如果不支持的话，可以替换回0.5.2，在FAQ有写

**Comment by burkgames** [comment]
另外有一个小建议，处理序列图为Apng时 ，是同时处理而非序列处理，打开任务管理器，好多进程，电脑卡爆了…………😂

**Comment by dreampiggy** [comment]
@burkgames 当时有人要求要最大化利用硬件性能，所以现在其实全并行处理，并行读取PNG文件，并行调用pngout来优化单个PNG，当全部处理完成，使用apngasm合成为一个APNG动图。原来就是串行执行的，会非常慢……
看这个：https://github.com/iSparta/iSparta/issues/10

多进程其实是那个pngout的进程，每个PNG文件处理会开一个进程。可以考虑给这个并行处理设置个上限，比如每组10个之类的。但是感觉一般来说这种转换器不都是一次性的吗，最大化效率比较好……

**Comment by dreampiggy** [comment]
另外，那个提示文案确实是写错了，应该只有APNG转换器会提示这个，apng2webp的叫做”转换失败！<br>请检查APNG文件格式“

**Comment by burkgames** [comment]
可以有个勾选来选择并行还是串行，体验更好一点就是可以自行控制并行的数量~
我 i7 16G GTX660处理一个大尺寸、1百多帧的动画，还是卡的飞爆~
apng2webp 转换失败的问题，应该与 webp 版本有关，PC win7 转换失败，笔记本win10转换没啥问题

**Comment by dreampiggy** [comment]
麻烦一件事，你能用Windows 7，替换一下cwebp.exe和webpmux.exe这两个webp程序，然后再试试看吗？我确认一下是不是有兼容问题。参考这个[FAQ](https://github.com/iSparta/iSparta/wiki/FAQ)第一条替换，里面的路径应该是`iSparta/package.nw/app/libs/webp/win64/`

下载地址：
https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-0.6.0-windows-x64-no-wic.zip
下载解压，在`bin/`下就有

**Comment by burkgames** [comment]
webp版本：0.6.0
1、替换webp 0.6.0，PNG转APNG无误
2、APNG转Webp出现错误弹框

webp版本：0.5.2
1、替换webp 0.6.0，PNG转APNG无误
2、APNG转Webp出现错误弹框

然后我吧这两个版本生成的APNG放到 win10 环境下来用0.6.0版本可以正常转Webp....

**Comment by dreampiggy** [comment]
有点神奇。这样，能不能麻烦你，通过命令行来启动。就是在iSparta的目录下，打开一个命令提示符（或者PowerShell更好）切换到当前目录下（可以直接在资源管理器的地址栏输入powershell启动），然后直接`.\iSparta.exe`来启动，再试试转换apng2webp。如果有错误，会有命令行提示XXX error，还有一些“stdout:”, "stderr:"，你把整个命令行的输出发出来我看看。。主要我这边没有Windows 7可以测试。。

**Comment by dreampiggy** [comment]
感觉应该搞一个日志收集的模块了，原来直接打印出来错误到提示上，但是看上去不好……

**Comment by burkgames** [comment]
我在win64文件夹下打开了 CMD.exe 
输入 .\iSparta.exe，然后拉起了转换工具，将之前的APNG转为webp，只有工具上的错误弹框，CMD中没有命令行提示。。。

**Comment by dreampiggy** [comment]
@burkgames 试试直接这样执行
`.\iSparta.exe --enable-logging`，然后操作直到报错。会在当前目录下生成个debug.log，发上来？

**Comment by burkgames** [comment]
[debug.txt](https://github.com/iSparta/iSparta/files/1259281/debug.txt)

**Comment by dreampiggy** [comment]
(Couldn't access Windows Imaging Component (are you running Windows XP SP3 or newer?)

服了，操作系统不支持Windows的自带的图片解码库，我替换成no-wic了，你前面测试的时候，是不是还下载的不带non-wic后缀的那个`libwebp-0.6.0-windows-x64.zip`？你试试替换下载那个non-wic.zip再看看。就是这个（不用测试0.5.2了）：https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-0.6.0-windows-x64-no-wic.zip

**Comment by burkgames** [comment]
替换后，成功转了一个，但是我尝试用一个大尺寸的时候，出现了这个问题。。。。


[11344:0829/174502:INFO:CONSOLE(117)] ""Compiling all doT templates..."", source: E:\Tools\win64\node_modules\dot\index.js (117)
[11344:0829/174502:INFO:CONSOLE(134)] ""Compiling index.dot to function"", source: E:\Tools\win64\node_modules\dot\index.js (134)
[11344:0829/174502:INFO:CONSOLE(0)] "Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.", source:  (0)
[11344:0829/174905:INFO:CONSOLE(304)] ""stdout: "", source:  (304)
[11344:0829/174905:INFO:CONSOLE(305)] ""stderr: \uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u032B\uFFFD\uFFFD\uFFFD\uFFFD\r\n"", source:  (305)
[11344:0829/174905:INFO:CONSOLE(218)] "", source:  (218)

**Comment by dreampiggy** [comment]
完整的日志有吗（继续用那种`.\iSparta.exe --enable-logging`方式帮忙发一下看看）……或者可否把图片发来我看看（如果不是版权图的话）？

**Comment by burkgames** [comment]
这个就是完整的日志 资源明天发你吧

**Comment by burkgames** [comment]
文件和LOG
https://share.weiyun.com/e60afdd6da8c5d9f85d3726b85961bef
已经转成APNG了。。。

**Comment by dreampiggy** [comment]
本地用无论是iSparta还是一个命令行的[apng2webp](https://github.com/Benny-/apng2webp)都能正常转换。怀疑大尺寸的时候本身WebP的那个webpmux程序会挂掉，这个估计只能给WebP项目提Bug了，转换器本身没办法处理……一般来说避免这么大的动图（压缩比75%，Animated WebP都10MB，可怕）。。暂时不知道怎么修复，不过WebP确实应该使用non-wic的版本，否则某些客户端没带Windows Image Component库的话就会出问题，之后会出一个Fix release版本。

**Comment by burkgames** [comment]
你是说如果自带了wic的版本是可以转化我发的文件么？

**Comment by dreampiggy** [comment]
@burkgames 我之后测试一下，手边暂时只有macOS和Ubuntu，这两个上面都是正常可以转换的。感觉有可能是non-wic版本存在问题，因为是通过MinGW编译的产物而不是原生VC++，可能有内存问题。如果不行的话还是使用普通的libwebp，对于遇到普通libwebp无法运行的用户，在FAQ里面写明替换non-WIC版本的相关事项。

**Comment by dreampiggy** [comment]
Fixed in [ver 2.1.2](https://github.com/iSparta/iSparta/releases/tag/2.1.2)

最后2.1.2版本，仅仅修复那个提示语（提示改为请检查APNG格式）。对于no-wic版本的webp二进制库，决定还是放到FAQ里面，如果遇到问题自行替换。
