### ISSUE TITLE
win7下转换序列帧（80帧）为APNG格式时，真个电脑很卡，基本不能用其它软件

### ISSUE THREAD

**Issue by longyc627** [iSparta/iSparta#22]

**Comment by jeakey** [comment]
@longyc627 近期在编写新版本，主要是解决APNG压缩和转换问题，敬请期待

**Comment by dreampiggy** [comment]
应该是最新版本（2.2.1），在APNG转换器上，使用了完全的并行处理，对每个原始PNG都会调用一次pngout（无损）或者pngquant（有损压缩）命令，对于大量序列帧会开大量进程。之后可以考虑对进程上限加以限制，每次分组处理（比如最多5个同时处理）。

如果真的在意转换时的其他应用运行效率，先试试2.1.0版本，不过这个版本的APNG转换器的实现方式和2.1.1版本不同，转换产物可能压缩率不高。

**Comment by dreampiggy** [comment]
之后我回滚一下APNG转换器代码吧，出一个bug fix版。之前改动的时候，没有考虑到pngquant所带来的图片压缩问题，可能反而有损压缩的APNG大小会比无损压缩要大。如果不着急，也可以等待9月中左右的大版本更新。

**Comment by dreampiggy** [comment]
Fixed in [ver 2.1.2](https://github.com/iSparta/iSparta/releases/tag/2.1.2)

2.1.2版，在PNG转APNG的时候，每帧图片按顺序处理，不会出现任何并行处理。CPU肯定非常开心。
如果期待更高转换速度但是又不会太影响CPU占用率的，可以等待新版。
