### ISSUE TITLE
合成webp文件太大

### ISSUE THREAD

**Issue by ljyao** [iSparta/iSparta#24]
以前无损转apng，再无损转webp  2.3mb
现在直接合成webp，7mb

**Comment by ljyao** [comment]
而且解码速度没有老版本快，慢2-3倍

**Comment by jeakey** [comment]
我们看看是什么原因，是mac还是windows？

**Comment by ljyao** [comment]
mac

**Comment by yikfun** [comment]
新版合成webp图片没有对图片进行压缩处理，所以比较大。
这个问题会在下个版本修复，感谢反馈~

**Comment by yikfun** [comment]
@ljyao 新的版本iSparta3.1已修复以上问题，可以更新体验。
