### ISSUE TITLE
关于视频转换动态图

### ISSUE THREAD

**Issue by zihengCat** [iSparta/iSparta#31]
你们好！感谢你们创造出 iSparta 工具，为更多的人提供方便。毕竟不是所有人都会写脚本，使用命令行工具的，开发这样一款 GUI 工具，普通用户也能享受新技术带来的便利～
看到你们的 **To-Do List** 上有一项：*视频转动态图*。
喵这里就写了个小工具，可以将**视频文件转换为PNG序列图**，搭配 iSparta 使用。
原理与 [iSparta-video](https://github.com/iSparta/iSparta-video) 类似，为`FFmpeg`制作了一枚前端GUI界面，处理工作交给`FFmpeg`，使用`electron`开发框架实现跨平台。
**iSparta 项目组有没有兴趣收容一下呐。**
项目地址：https://github.com/zihengCat/video2pngs
> PS: 名字和LOGO借用了 iSparta ，见谅呐，如有侵权，马上删除。
> PPS：喵不会前端和`electron`框架，看`electron`文档现学现做，2天写出来的...

**Comment by yikfun** [comment]
你好，感谢你对iSparta的关注。
视频转动态图这个功能我们计划整合进工具里，就不收纳了。
名字和LOGO的确会侵权哈，建议你更换下，多谢 :)
