### ISSUE TITLE
可以转a webp么?

### ISSUE THREAD

**Issue by zhfish** [iSparta/iSparta#4]
看了apng和a webp 还是对a webp比较感兴趣

**Comment by hkz404** [comment]
该功能暂不支持，后续可能会增加

**Comment by zhfish** [comment]
webp和webp animal 在ios和android里是比较容易支持的.
希望可以尽早支持转换啊

**Comment by hkz404** [comment]
目前支持 APNG 转 aWebp，请试用：https://github.com/dreampiggy/iSparta/releases
